<?php
require_once dirname(__DIR__) . '/_bootstrap.php';
require_once dirname(__DIR__, 3) . '/app/controllers/CustomerPortalController.php';
$viewData = (new CustomerPortalController())->incidentDetailsPage($_GET, $_POST, strtoupper((string) ($_SERVER['REQUEST_METHOD'] ?? 'GET')));
if (isset($viewData['redirect'])) { header('Location: ' . customer_url($viewData['redirect']), true, 303); exit; }
$incident=$viewData['incident']; require dirname(__DIR__) . '/components/layout/feature-start.php';
?>
<p><a class="text-link" href="<?=htmlspecialchars(customer_url('incidents/index.php'),ENT_QUOTES,'UTF-8')?>">&larr; Back to incidents</a></p>
<?php foreach($viewData['errors'] as $error):?><div class="alert alert--error"><p><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></p></div><?php endforeach;?>
<?php if($viewData['database_error']):?><section class="empty-state"><h2>Incident details unavailable</h2><p>Please try again later.</p></section>
<?php elseif(!is_array($incident)):?><section class="empty-state"><h2>Incident not found</h2><p>This incident does not exist or does not belong to your account.</p></section>
<?php else:?><div class="feature-detail-grid"><section class="card"><div class="card__header"><div><p class="eyebrow">Incident #<?= (int)$incident['id']?></p><h2><?=htmlspecialchars($incident['make'].' '.$incident['model'],ENT_QUOTES,'UTF-8')?></h2></div><span class="status-badge status-badge--warning"><?=htmlspecialchars(ucfirst($incident['status']),ENT_QUOTES,'UTF-8')?></span></div><dl class="feature-detail-list"><div><dt>Booking</dt><dd>#<?=(int)$incident['booking_id']?></dd></div><div><dt>Severity</dt><dd><?=htmlspecialchars(ucfirst($incident['severity']),ENT_QUOTES,'UTF-8')?></dd></div><div><dt>Incident date</dt><dd><?=htmlspecialchars(date('d M Y, h:i A',strtotime($incident['incident_date'])),ENT_QUOTES,'UTF-8')?></dd></div><div><dt>Created</dt><dd><?=htmlspecialchars(date('d M Y, h:i A',strtotime($incident['created_at'])),ENT_QUOTES,'UTF-8')?></dd></div><div class="feature-detail-list__wide"><dt>Description</dt><dd><?=nl2br(htmlspecialchars($incident['description'],ENT_QUOTES,'UTF-8'))?></dd></div></dl><a class="button button--secondary" href="<?=htmlspecialchars(customer_url('bookings/details.php?id='.(int)$incident['booking_id']),ENT_QUOTES,'UTF-8')?>">Booking Details</a></section>
<aside class="card"><h2>Replacement information</h2><?php if(!is_array($incident['replacement'])):?><p>No replacement offer is linked to this incident. Customers cannot assign a replacement vehicle.</p><?php else:?><p><strong><?=htmlspecialchars(trim(($incident['replacement']['replacement_make']??'').' '.($incident['replacement']['replacement_model']??''))?:'Vehicle not assigned',ENT_QUOTES,'UTF-8')?></strong></p><p>Operational status: <?=htmlspecialchars(ucfirst($incident['replacement']['status']),ENT_QUOTES,'UTF-8')?></p><?php if(is_array($viewData['replacement_decision'])):?><span class="demo-label">Demo decision</span><p><?=htmlspecialchars(ucfirst($viewData['replacement_decision']['decision']),ENT_QUOTES,'UTF-8')?> recorded in this session only.</p><?php elseif(empty($viewData['demo_mode'])):?><p>Customer decision storage is unavailable because demo workflows are disabled and the live schema has no Customer decision field.</p><?php else:?><span class="demo-label">Prototype workflow</span><p>The live schema has no Customer decision field. This form records only isolated demo-session state and does not alter the replacement request.</p><form class="feature-form feature-form--compact" method="post" action="<?=htmlspecialchars(customer_url('incidents/details.php?id='.(int)$incident['id']),ENT_QUOTES,'UTF-8')?>"><?=CustomerCsrf::field()?><input type="hidden" name="incident_id" value="<?=(int)$incident['id']?>"><label for="replacement-decision">Demo decision</label><select id="replacement-decision" name="decision" required><option value="accept">Accept offer</option><option value="reject">Reject offer</option></select><label for="replacement-reason">Optional reason</label><textarea id="replacement-reason" name="reason" maxlength="300"></textarea><button class="button button--secondary" type="submit">Record demo decision</button></form><?php endif;?><?php endif;?></aside></div><?php endif;?>
<?php require dirname(__DIR__) . '/components/layout/feature-end.php'; ?>
