<?php
require_once dirname(__DIR__) . '/_bootstrap.php';
require_once dirname(__DIR__, 3) . '/app/controllers/CustomerPortalController.php';
$viewData=(new CustomerPortalController())->inspectionDetailsPage($_GET); $result=$viewData['result']; require dirname(__DIR__) . '/components/layout/feature-start.php';
?>
<p><a class="text-link" href="<?=htmlspecialchars(customer_url('inspection/index.php'),ENT_QUOTES,'UTF-8')?>">&larr; Back to inspections</a></p>
<?php if($viewData['database_error']):?><section class="empty-state"><h2>Inspection report unavailable</h2><p>Please try again later.</p></section>
<?php elseif(!is_array($result)):?><section class="empty-state"><h2>Booking not found</h2><p>This booking does not exist or does not belong to you.</p></section>
<?php else:?><section class="card"><div class="card__header"><div><p class="eyebrow">Booking #<?=(int)$result['booking']['id']?></p><h2><?=htmlspecialchars($result['booking']['make'].' '.$result['booking']['model'],ENT_QUOTES,'UTF-8')?></h2></div><span class="status-badge status-badge--info">Read-only</span></div><p>Registration: <?=htmlspecialchars($result['booking']['license_plate'],ENT_QUOTES,'UTF-8')?>. Customers cannot create, edit, or delete inspection records.</p></section>
<?php if($result['inspections']===[]):?><section class="empty-state"><h2>No inspection report is available for this booking yet.</h2><p>Authorized staff will record inspection information when applicable.</p></section>
<?php else:?><div class="feature-card-list"><?php foreach($result['inspections'] as $inspection):?><article class="card"><div class="card__header"><div><p class="eyebrow"><?=htmlspecialchars(ucwords(str_replace('_',' ',$inspection['inspection_type'])),ENT_QUOTES,'UTF-8')?></p><h2><?=htmlspecialchars(date('d M Y, h:i A',strtotime($inspection['inspection_date'])),ENT_QUOTES,'UTF-8')?></h2></div><span class="status-badge status-badge--info"><?=htmlspecialchars(ucwords(str_replace('_',' ',$inspection['status'])),ENT_QUOTES,'UTF-8')?></span></div><dl class="feature-detail-list"><div><dt>Odometer</dt><dd><?=number_format((int)$inspection['odometer_reading'])?> km</dd></div><div><dt>Fuel level</dt><dd><?=htmlspecialchars($inspection['fuel_level'],ENT_QUOTES,'UTF-8')?></dd></div><div class="feature-detail-list__wide"><dt>Exterior condition</dt><dd><?=nl2br(htmlspecialchars($inspection['exterior_condition'],ENT_QUOTES,'UTF-8'))?></dd></div><div class="feature-detail-list__wide"><dt>Interior condition</dt><dd><?=nl2br(htmlspecialchars($inspection['interior_condition'],ENT_QUOTES,'UTF-8'))?></dd></div><div class="feature-detail-list__wide"><dt>Comments</dt><dd><?=nl2br(htmlspecialchars($inspection['comments']?:'No comments recorded.',ENT_QUOTES,'UTF-8'))?></dd></div></dl><p class="form-hint">Recorded by authorized staff.</p></article><?php endforeach;?></div><?php endif;?><?php endif;?>
<?php require dirname(__DIR__) . '/components/layout/feature-end.php'; ?>
