<?php
// Reports Page
?>

<header class="page-header">
    <div>
        <h1>Reports</h1>
        <p>Generate and download booking, revenue, payment and system reports.</p>
    </div>
</header>

<section class="card filters-card reports-filters">

    <div class="filters-card-header">
        <div class="filter-icon">
            📊
        </div>

        <div>
            <h2 class="section-label">Report Filters</h2>
            <p class="section-description">
                Generate reports by selecting the report type and date range.
            </p>
        </div>
    </div>

    <div class="filter-grid">

        <label class="filter-group">
            <span>Report Type</span>
            <select>
                <option>All Reports</option>
                <option>Revenue Report</option>
                <option>Bookings Report</option>
                <option>Payment Report</option>
                <option>Vehicle Report</option>
                <option>Driver Report</option>
                <option>Vehicle Owner Report</option>
                <option>Incident Report</option>
            </select>
        </label>

        <label class="filter-group">
            <span>From Date</span>
            <input type="date">
        </label>

        <label class="filter-group">
            <span>To Date</span>
            <input type="date">
        </label>

        <div class="filter-group">
            <span>&nbsp;</span>

            <div class="filter-actions">
                <button class="btn btn-primary">
                    Generate
                </button>

                <button class="btn btn-outline">
                    Reset
                </button>
            </div>

        </div>

    </div>

</section>

<section class="card wide-card">

    <div class="reports-table table-header">

        <span>Report</span>
        <span>Generated Date</span>
        <span>Period</span>
        <span>Format</span>
        <span>Generated By</span>
        <span>Action</span>

    </div>

    <div class="reports-table table-row">

        <span>
            <strong>Monthly Revenue Report</strong><br>
            <small>Revenue Summary</small>
        </span>

        <span>31 Jul 2026</span>

        <span>July 2026</span>

        <span>
            <span class="status-pill status-success">
                PDF
            </span>
        </span>

        <span>Admin</span>

        <div class="row-actions">

            <button class="btn btn-outline">
                Download
            </button>

        </div>

    </div>

    <div class="reports-table table-row">

        <span>
            <strong>Booking Summary</strong><br>
            <small>Weekly Report</small>
        </span>

        <span>30 Jul 2026</span>

        <span>Weekly</span>

        <span>
            <span class="status-pill status-warning">
                Excel
            </span>
        </span>

        <span>Admin</span>

        <div class="row-actions">

            <button class="btn btn-outline">
                Download
            </button>

        </div>

    </div>

    <div class="reports-table table-row">

        <span>
            <strong>Payment Verification</strong><br>
            <small>Payments</small>
        </span>

        <span>29 Jul 2026</span>

        <span>Monthly</span>

        <span>
            <span class="status-pill status-success">
                PDF
            </span>
        </span>

        <span>Admin</span>

        <div class="row-actions">

            <button class="btn btn-outline">
                Download
            </button>

        </div>

    </div>

    <div class="reports-table table-row">

        <span>
            <strong>Vehicle Performance</strong><br>
            <small>Vehicle Usage</small>
        </span>

        <span>28 Jul 2026</span>

        <span>Monthly</span>

        <span>
            <span class="status-pill status-warning">
                Excel
            </span>
        </span>

        <span>Admin</span>

        <div class="row-actions">

            <button class="btn btn-outline">
                Download
            </button>

        </div>

    </div>

    <div class="reports-table table-row">

        <span>
            <strong>Incident Summary</strong><br>
            <small>Safety Report</small>
        </span>

        <span>27 Jul 2026</span>

        <span>Quarterly</span>

        <span>
            <span class="status-pill status-success">
                PDF
            </span>
        </span>

        <span>Admin</span>

        <div class="row-actions">

            <button class="btn btn-outline">
                Download
            </button>

        </div>

    </div>

</section>